[package]
name = "soft_server_lib"
version = "0.1.0"
edition = "2018"

[dependencies]
soft_shared_lib = { path = "../soft_shared_lib" }
atomic = "0.5"
rand = "0.8.4"
sha2 = "0.9.5"
hex-literal = "0.3.1"

[dev-dependencies]
tempdir = "0.3.7"
hex-literal = "0.3.1"