[package]
name = "soft_shared_lib"
version = "0.1.0"
edition = "2018"

[dependencies]
sha2 = "0.9.5"
byteorder = "1.4.3"
num = "0.4.0"
num-derive = "0.3"
num-traits = "0.2"
rand = "0.8.4"

[dev-dependencies]
hex-literal = "0.3.1"
